---
version : 1
dependencies:
   galaxy: requirements.yml
   python: requirements.txt
   system: bindep.txt
additional_build_steps:
   append:
     - RUN alternatives --set python /usr/bin/python3
     - RUN pip3 uninstall --yes ansible-runner && pip3 install ansible-runner==2.0.0a1
     - USER 1000
     - ADD run.sh /run.sh
     - CMD /run.sh
     - RUN git lfs install

